# -*- coding: utf-8 -*-
"""Model PTDM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zu5SASmnzlKEZuiJyKZCNTNq7YVqQvQI
"""

import pandas as pd
import numpy as np

df = pd.read_csv("Data1_2026.csv")
df.head()

df.shape

df.info()

df['PTDM'].value_counts()

import matplotlib.pyplot as plt

df['PTDM'].value_counts().plot(kind='bar')
plt.title("Distribution de la variable PTDM")
plt.xlabel("PTDM")
plt.ylabel("Nombre de patients")
plt.show()

cols_to_drop = [
    'num_dossier',
    'filter_$',
    'deces_post_PTDM',
    'delai_deces_PTDM',
    'delai_dialyse_PTDM'
]

df = df.drop(columns=cols_to_drop)

df.isnull().sum().sort_values(ascending=False).head(10)

from sklearn.impute import SimpleImputer

num_cols = df.select_dtypes(include=['float64', 'int64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

num_imputer = SimpleImputer(strategy='median')
df[num_cols] = num_imputer.fit_transform(df[num_cols])

cat_imputer = SimpleImputer(strategy='most_frequent')
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

df.columns[df.columns.str.contains("HBA", case=False)]

df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

X = df.drop('PTDM', axis=1)
y = df['PTDM']

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(
    penalty='l2',
    C=1.0,
    solver='liblinear',
    max_iter=1000
)

log_reg.fit(X_train, y_train)

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(
    penalty='l2',
    C=1.0,
    solver='liblinear',
    max_iter=1000
)

log_reg.fit(X_train, y_train)

y_pred = log_reg.predict(X_test)
y_proba = log_reg.predict_proba(X_test)[:, 1]

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(y_test, y_proba)
auc = roc_auc_score(y_test, y_proba)

plt.plot(fpr, tpr, label=f"AUC = {auc:.2f}")
plt.plot([0,1], [0,1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Logistic Regression")
plt.legend()
plt.show()

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    random_state=42,
    class_weight='balanced'
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
y_proba_rf = rf.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

importances = rf.feature_importances_
indices = np.argsort(importances)[-10:]

plt.barh(range(len(indices)), importances[indices])
plt.yticks(range(len(indices)), X.columns[indices])
plt.title("Top 10 variables importantes - Random Forest")
plt.show()

from sklearn.svm import SVC

svm = SVC(
    kernel='rbf',
    C=1,
    gamma='scale',
    probability=True,
    class_weight='balanced'
)

svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)
y_proba_svm = svm.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("\nClassification Report:\n", classification_report(y_test, y_pred_svm))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

fpr_svm, tpr_svm, _ = roc_curve(y_test, y_proba_svm)
auc_svm = roc_auc_score(y_test, y_proba_svm)

plt.plot(fpr_svm, tpr_svm, label=f"SVM AUC = {auc_svm:.2f}")
plt.plot([0,1], [0,1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - SVM")
plt.legend()
plt.show()

from sklearn.metrics import roc_auc_score, accuracy_score


auc_lr = roc_auc_score(y_test, y_proba)


auc_rf = roc_auc_score(y_test, y_proba_rf)

auc_svm = roc_auc_score(y_test, y_proba_svm)

results = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest', 'SVM'],
    'AUC': [auc_lr, auc_rf, auc_svm],
    'Accuracy': [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_svm)
    ]
})

results

import numpy as np

idx = np.random.randint(0, X_test.shape[0])

patient = X_test[idx]
true_label = y_test.iloc[idx]

print("Vrai diagnostic PTDM :", true_label)

pred_lr = log_reg.predict(patient.reshape(1, -1))[0]
proba_lr = log_reg.predict_proba(patient.reshape(1, -1))[0, 1]


pred_rf = rf.predict(patient.reshape(1, -1))[0]
proba_rf = rf.predict_proba(patient.reshape(1, -1))[0, 1]

pred_svm = svm.predict(patient.reshape(1, -1))[0]
proba_svm = svm.predict_proba(patient.reshape(1, -1))[0, 1]

results_patient = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest', 'SVM'],
    'Prediction (0=No PTDM, 1=PTDM)': [pred_lr, pred_rf, pred_svm],
    'Probability of PTDM': [proba_lr, proba_rf, proba_svm]
})

results_patient

def test_patient(X_patient):
    return pd.DataFrame({
        'Model': ['Logistic Regression', 'Random Forest', 'SVM'],
        'Probability PTDM': [
            log_reg.predict_proba(X_patient)[0,1],
            rf.predict_proba(X_patient)[0,1],
            svm.predict_proba(X_patient)[0,1]
        ]
    })

test_patient(patient.reshape(1, -1))

def predict_ptdm_from_dict(patient_dict):
    """
    patient_dict : dictionnaire {colonne: valeur}
    """

    patient_df = pd.DataFrame([patient_dict])


    patient_df = pd.get_dummies(patient_df)


    patient_df = patient_df.reindex(columns=X.columns, fill_value=0)


    patient_scaled = scaler.transform(patient_df)
    results = pd.DataFrame({
        "Model": ["Logistic Regression", "Random Forest", "SVM"],
        "Prediction (0=No PTDM, 1=PTDM)": [
            log_reg.predict(patient_scaled)[0],
            rf.predict(patient_scaled)[0],
            svm.predict(patient_scaled)[0]
        ],
        "Probability of PTDM": [
            log_reg.predict_proba(patient_scaled)[0,1],
            rf.predict_proba(patient_scaled)[0,1],
            svm.predict_proba(patient_scaled)[0,1]
        ]
    })

    return results

patient_example = {
    'sexe_receveur_M': 1,
    'age_receveur_TR': 48,
    'obésité_pre_TR_receveur': 1,
    'HTA_pre_TR_receveur': 1,
    'intolerance_glucose_receveur': 0,
    'TABAC': 0,
    'Alcool': 0,
    'glycémie_pre_TR_R': 1.1,
    'HbA1c_pre_TR_R': 5.9,
    'Huricémie_pre_TR_receveur': 380,
    'durée_dialyse_année': 3,
    'age_donneur': 55,
    'HTA_donneur': 1
}

predict_ptdm_from_dict(patient_example)

!pip install ipywidgets

import ipywidgets as widgets
from IPython.display import display, clear_output

age = widgets.IntSlider(
    value=45, min=18, max=80, step=1,
    description='Age:',
    style={'description_width': 'initial'}
)

sexe = widgets.Dropdown(
    options=[('Homme', 1), ('Femme', 0)],
    description='Sexe:'
)

obesite = widgets.Dropdown(
    options=[('Non', 0), ('Oui', 1)],
    description='Obésité:'
)

hta = widgets.Dropdown(
    options=[('Non', 0), ('Oui', 1)],
    description='HTA:'
)

glycemie = widgets.FloatSlider(
    value=1.0, min=0.6, max=2.5, step=0.01,
    description='Glycémie:',
    style={'description_width': 'initial'}
)

hba1c = widgets.FloatSlider(
    value=5.5, min=4.0, max=10.0, step=0.1,
    description='HbA1c:',
    style={'description_width': 'initial'}
)

duree_dialyse = widgets.FloatSlider(
    value=2, min=0, max=10, step=0.5,
    description='Durée dialyse (ans):',
    style={'description_width': 'initial'}
)

age_donneur = widgets.IntSlider(
    value=40, min=18, max=80, step=1,
    description='Age donneur:',
    style={'description_width': 'initial'}
)

button = widgets.Button(
    description=' Prédire le risque PTDM',
    button_style='success'
)

output = widgets.Output()

def on_button_clicked(b):
    with output:
        clear_output()

        patient = {
            'age_receveur_TR': age.value,
            'sexe_receveur_M': sexe.value,
            'obésité_pre_TR_receveur': obesite.value,
            'HTA_pre_TR_receveur': hta.value,
            'glycémie_pre_TR_R': glycemie.value,
            'HbA1c_pre_TR_R': hba1c.value,
            'durée_dialyse_année': duree_dialyse.value,
            'age_donneur': age_donneur.value
        }

        result = predict_ptdm_from_dict(patient)
        display(result)

button.on_click(on_button_clicked)

ui = widgets.VBox([
    age,
    sexe,
    obesite,
    hta,
    glycemie,
    hba1c,
    duree_dialyse,
    age_donneur,
    button,
    output
])

display(ui)